version: "3"

services:
  sonarqube:
    image: sonarqube:6.7.1
    container_name: Sonarqube
    restart: always
    environment:
      - SONARQUBE_JDBC_USERNAME=riansakti
      - SONARQUBE_JDBC_PASSWORD=R4h4s14
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
      - /media/sonar-golang-plugin-1.2.11-rc3.jar:/opt/sonarqube/extensions/plugins/sonar-golang-plugin-1.2.11-rc3.jar

  db:
    image: postgres:10.1
    container_name: PostgreSQL
    restart: always
    environment:
      - POSTGRES_USER=riansakti
      - POSTGRES_PASSWORD=R4h4s14
      - POSTGRES_DB=sonarqube
    volumes:
      - sonarqube_db:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql_data:
  sonarqube_bundled-plugins:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_db:
  sonarqube_extensions:
